# Generated by Django 5.1.6 on 2025-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=4)),
                ('phone', models.IntegerField(max_length=30)),
            ],
        ),
    ]
