# Generated by Django 5.1.6 on 2025-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.IntegerField(),
        ),
    ]
