# Generated by Django 5.1.6 on 2025-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='play_cricket',
            field=models.CharField(default='yes', max_length=5),
            preserve_default=False,
        ),
    ]
