# Generated by Django 5.1.6 on 2025-02-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_phone_student_play_cricket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
