# Generated by Django 5.1.6 on 2025-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('branch', models.CharField(max_length=5)),
                ('backlogs', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
